services:
  local-s3:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3

  local-gcs:
    image: fsouza/fake-gcs-server
    ports:
      - "4443:4443"
    command: ["-scheme", "http", "-port", "4443"]

  local-azure:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
    command: azurite-blob --blobHost 0.0.0.0
